app = "lifesafetyguarantee"
console_command = "/code/manage.py shell"
primary_region = "nrt"

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
PORT = "8000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[statics]]
guest_path = "/code/static"
tigris_bucket = ""
url_prefix = "/static/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
